// Generated by CoffeeScript 1.7.1
(function() {
  var Building;

  Building = (function() {
    var _class;

    function Building() {
      return _class.apply(this, arguments);
    }

    _class = Building.model(– > arel.Debug.log('Loaded: ', model));

    return Building;

  })();

}).call(this);
