// Generated by CoffeeScript 1.7.1
(function() {
  var objectClickHandler, showingInfo;

  requirejs.config({
    baseurl: 'js'
  });

  showingInfo = false;

  arel.sceneReady(function() {
    var house, model;
    arel.Debug.log('Loading scene...');
    model = arel.Scene.getObject('family_house');
    house = new Building(model);
    arel.Events.setListener(house.model, function(obj, type, params) {
      return objectClickHandler(obj, type, params);
    });
  });

  objectClickHandler = function(obj, type, params) {
    if (type && type === arel.Events.Object.ONTOUCHSTARTED) {
      if (showingInfo) {
        document.getElementById('info').style.display = 'none';
        document.getElementById('name').innerHTML = obj.title;
        showingInfo = false;
      } else {
        document.getElementById('info').style.display = 'block';
        document.getElementById('name').innerHTML = obj.title;
        showingInfo = true;
      }
    }
  };

}).call(this);
