// Generated by CoffeeScript 1.7.1
(function() {
  var objectClickHandler, showingInfo;

  showingInfo = false;

  arel.sceneReady(function() {
    var man;
    man = arel.Scene.getObject('man');
    man.setScale(new arel.Vector3D(2, 2, 2));
    man.setTitle("Karel");
    arel.Events.setListener(man, function(obj, type, params) {
      return objectClickHandler(obj, type, params);
    });
  });

  objectClickHandler = function(obj, type, params) {
    if (type && type === arel.Events.Object.ONTOUCHSTARTED) {
      if (showingInfo) {
        document.getElementById('info').style.display = 'none';
        document.getElementById('name').innerHTML = obj.title;
        showingInfo = false;
      } else {
        document.getElementById('info').style.display = 'block';
        document.getElementById('name').innerHTML = obj.title;
        showingInfo = true;
      }
    }
  };

}).call(this);
